---

- hosts: lb
  become: true

  tasks: 
     - name: Install EPEL release for nginx
       yum: name=epel-release state=present

     - name: install nginx
       yum:  name=nginx state=installed

     - name: state nginx services
       service: name=nginx state=started enabled=yes

     - #replace:
        #      path: /etc/nginx/nginx.conf
         #     regexp: 'conf.d'
          #    replace: 'sites-enabled'
           #   backup: yes

     - name: make directory
       file: path=/etc/nginx/sites-available state=directory
       notify: restart nginx


     - name: configure ngnix site
       template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
       notify: restart nginx

     - name: make directory
       file: path=/etc/nginx/sites-enabled state=directory
       notify: restart nginx

 
     - name: activate nginx site
       file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
       notify: restart nginx

  handlers:
     - name: restart nginx  
       service: name=nginx state=restarted  
