---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx service
      command: systemctl status nginx
    
    - name: verify nginx listening on port 80
      wait_for: port=80 timeout=1
 
- hosts: production
  become: true
  tasks:
    - name: verify httpd service
      command: systemctl status httpd
    
    - name: verify httpd is listing on port 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify mysqld service
      command: systemctl status mysqld

    - name: Verify mysql is listing of port 3306
      wait_for: port=3306 timeout=1

- hosts: control
  become: true
  tasks:
    - name: verify back end response
      uri: url=http://{{item}} return_content=yes
      with_items: 
               - lb
      register: lb_index

    - fail: msg="index failed to return contents"
      when: "'Hello, from sandeep' not in item.content"
      with_items: "{{lb_index.results}}"

- hosts: loadbalancer
  become: true
  tasks:
    - name: verify end to end response
      uri: url=http://{{item}} return_content=yes
      with_items:
             - prod01
             - prod02
      register: app_index

    - fail: msg="index failed to return contents"
      when: "'Hello, from sandeep {{item.item}}!' not in item.content"
      with_items: "{{app_index.results}}"



    - debug: 
        var: lb_index.stout

