---
- hosts: production
  tasks:
      -  service: name=httpd state=stopped
      -  wait_for: port=80 state=stopped

- hosts: loadbalancer
  tasks:
      -  service: name=nginx state=stopped
      -  wait_for: port=80 state=drained

- hosts: database
  tasks:
     -  service: name=mysqld state=restarted
     -  wait_for: port=3306 state=started

- hosts: production
  tasks:
     - service: name=httpd state=started
     -  wait_for: port=80 state=started

- hosts: loadbalancer
  tasks:
     - service: name=nginx state=started
     - wait_for: port=80 state=started


